### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [1]:
import numpy as np
print(np.__version__)

2.2.2



### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [2]:
# Solution Here
# Q.1
list1 = [1,2,3,4,5] # List of number
arr1 = np.array(list1) # convert into np array
arr1

array([1, 2, 3, 4, 5])

In [3]:
#Q.2
list2 = [[1,3,6],  # 2D List
         [2,5,8],
         [7,9,4]]
arr2 = np.array(list2) # convert into np array
print(arr2)

[[1 3 6]
 [2 5 8]
 [7 9 4]]


In [4]:
# In another way 
arr2_ = np.array(range(1,10)).reshape(3,3)
arr2_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Q.3
arr3 = np.linspace(0,5,10)
arr3

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [6]:
# Solution Here
# Accessing the element 
element = arr2_[1,2]
element

np.int64(6)

In [7]:
# Slice the first two row and first two columns
slice_arr_ = arr2_[:2, :2]
slice_arr_

array([[1, 2],
       [4, 5]])

In [8]:
#Modify the value in the last row and first column to 100
arr2_[-1,0] = 100
arr2_

array([[  1,   2,   3],
       [  4,   5,   6],
       [100,   8,   9]])

### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [9]:
# Solution Here
data = arr2_
print(data.shape)
print(data.size)
print(data.dtype)

(3, 3)
9
int64


In [10]:
one_d = np.array([1,2,3,4,5]).reshape(5,1)
# one_f = one_d.reshape(5,1)
one_d

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
arr2_

array([[  1,   2,   3],
       [  4,   5,   6],
       [100,   8,   9]])

In [12]:
flatten = arr2_.flatten()
flatten

array([  1,   2,   3,   4,   5,   6, 100,   8,   9])

### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [13]:
# Solution Here
ad = np.array([1,2,3,5,6])

print(np.add(ad,5))


[ 6  7  8 10 11]


In [14]:
# Multiply
mul = arr2_
print(mul)
print()
print(np.multiply(mul,3))

[[  1   2   3]
 [  4   5   6]
 [100   8   9]]

[[  3   6   9]
 [ 12  15  18]
 [300  24  27]]


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]


### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [16]:
# Solution Here
one = np.ones([3,3])
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
lengh_one = np.array([2,5,8])
lengh_add = one + lengh_one
lengh_add

array([[3., 6., 9.],
       [3., 6., 9.],
       [3., 6., 9.]])