## Linear Algebra

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/ankitsubedi/Desktop/Ankit File/Data_science class/newenv/lib/python3.11/site-packages/numpy/__init__.py'>

# Creating Numpy Array

In [3]:
list1 = [2,3,4]
arr1 = np.array(list1)

In [4]:
arr1

array([2, 3, 4])

In [5]:
arr1.shape

(3,)

In [6]:
list2 = [[1,3,6],
         [2,5,8]]
arr2 = np.array(list2)

In [7]:
arr2

array([[1, 3, 6],
       [2, 5, 8]])

In [8]:
arr2.shape

(2, 3)

In [9]:
arr1.ndim



1

In [10]:
arr2.ndim

2

In [11]:
list3 = [[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12],
         [13,14,15,16]]

In [12]:
arr3 = np.array(list3)

In [13]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
arr3.shape

(4, 4)

In [15]:
arr3.ndim

2

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.zeros(shape = (5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(shape = (2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.full((2,2),7.8)

array([[7.8, 7.8],
       [7.8, 7.8]])

In [20]:
np.random.rand(2,3)

array([[0.9742342 , 0.86984275, 0.0272946 ],
       [0.56792192, 0.05584973, 0.14958075]])

In [21]:
np.linspace(start = 0,stop = 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.linspace(start = (0,1,2),stop = (10,20,30), num = 5, axis = 1)

array([[ 0.  ,  2.5 ,  5.  ,  7.5 , 10.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ],
       [ 2.  ,  9.  , 16.  , 23.  , 30.  ]])

In [23]:
np.random.randint(low = 4, high = 25, size = (2,3,2,3))

array([[[[ 9,  5, 24],
         [17,  5, 10]],

        [[23, 14,  5],
         [ 6,  7, 15]],

        [[ 4, 20,  4],
         [21, 15, 15]]],


       [[[12,  5, 19],
         [10, 13,  9]],

        [[23, 24, 18],
         [ 4, 15, 24]],

        [[ 4,  9, 12],
         [19, 11, 10]]]])