In [1]:
import numpy as np

In [2]:
arr = np.random.randint(10,50, size = (5,2,3))
arr

array([[[33, 22, 36],
        [19, 43, 37]],

       [[37, 25, 37],
        [21, 44, 45]],

       [[43, 13, 36],
        [32, 40, 33]],

       [[34, 28, 18],
        [24, 46, 34]],

       [[12, 21, 23],
        [26, 25, 22]]])

In [3]:
arr.shape

(5, 2, 3)

In [4]:
arr.ndim

3

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr_T = arr.T
arr_T

array([[[33, 37, 43, 34, 12],
        [19, 21, 32, 24, 26]],

       [[22, 25, 13, 28, 21],
        [43, 44, 40, 46, 25]],

       [[36, 37, 36, 18, 23],
        [37, 45, 33, 34, 22]]])

In [7]:
arr_T.shape

(3, 2, 5)

In [8]:
arr.shape

(5, 2, 3)

In [9]:
arr.reshape(3, 5, 2)

array([[[33, 22],
        [36, 19],
        [43, 37],
        [37, 25],
        [37, 21]],

       [[44, 45],
        [43, 13],
        [36, 32],
        [40, 33],
        [34, 28]],

       [[18, 24],
        [46, 34],
        [12, 21],
        [23, 26],
        [25, 22]]])

In [10]:
arr.reshape(3, 10)

array([[33, 22, 36, 19, 43, 37, 37, 25, 37, 21],
       [44, 45, 43, 13, 36, 32, 40, 33, 34, 28],
       [18, 24, 46, 34, 12, 21, 23, 26, 25, 22]])

In [11]:
arr.reshape(10,3)

array([[33, 22, 36],
       [19, 43, 37],
       [37, 25, 37],
       [21, 44, 45],
       [43, 13, 36],
       [32, 40, 33],
       [34, 28, 18],
       [24, 46, 34],
       [12, 21, 23],
       [26, 25, 22]])

In [27]:
arr.reshape(2,-1,3)

array([[[33, 22, 36],
        [19, 43, 37],
        [37, 25, 37],
        [21, 44, 45],
        [43, 13, 36]],

       [[32, 40, 33],
        [34, 28, 18],
        [24, 46, 34],
        [12, 21, 23],
        [26, 25, 22]]])

In [28]:
arr.flatten() #row to row

array([33, 22, 36, 19, 43, 37, 37, 25, 37, 21, 44, 45, 43, 13, 36, 32, 40,
       33, 34, 28, 18, 24, 46, 34, 12, 21, 23, 26, 25, 22])

In [33]:
arr.flatten("F")

array([33, 37, 43, 34, 12, 19, 21, 32, 24, 26, 22, 25, 13, 28, 21, 43, 44,
       40, 46, 25, 36, 37, 36, 18, 23, 37, 45, 33, 34, 22])

In [34]:
arr.sum()

np.int64(909)

In [44]:
arr.sum(axis= 1)

array([[52, 65, 73],
       [58, 69, 82],
       [75, 53, 69],
       [58, 74, 52],
       [38, 46, 45]])

In [47]:
arr.prod()

np.int64(-1208815192431919104)

In [46]:
arr.prod(dtype= float)

np.float64(5.095078976962852e+43)

In [48]:
arr.prod(axis = 0)

array([[21421224,  4204200, 19852128],
       [ 7967232, 87032000, 41098860]])

In [49]:
arr.prod(axis = 1)

array([[ 627,  946, 1332],
       [ 777, 1100, 1665],
       [1376,  520, 1188],
       [ 816, 1288,  612],
       [ 312,  525,  506]])

In [50]:
arr.cumsum()

array([ 33,  55,  91, 110, 153, 190, 227, 252, 289, 310, 354, 399, 442,
       455, 491, 523, 563, 596, 630, 658, 676, 700, 746, 780, 792, 813,
       836, 862, 887, 909])

In [51]:
arr.max()

np.int64(46)

In [52]:
arr.argmax()

np.int64(22)

In [58]:
arr.clip(20,30) #value netween 20 to 30

array([[[30, 22, 30],
        [20, 30, 30]],

       [[30, 25, 30],
        [21, 30, 30]],

       [[30, 20, 30],
        [30, 30, 30]],

       [[30, 28, 20],
        [24, 30, 30]],

       [[20, 21, 23],
        [26, 25, 22]]])

In [59]:
arr

array([[[33, 22, 36],
        [19, 43, 37]],

       [[37, 25, 37],
        [21, 44, 45]],

       [[43, 13, 36],
        [32, 40, 33]],

       [[34, 28, 18],
        [24, 46, 34]],

       [[12, 21, 23],
        [26, 25, 22]]])

In [62]:
arr1 = np.random.randint(low= -10, high= 10, size= (2,3))
arr2 = np.random.randint(low= 0, high= 10, size= (2,3))

In [63]:
arr1, arr2

(array([[ 3,  2, -7],
        [ 5, -2, -5]]),
 array([[6, 7, 4],
        [8, 1, 2]]))

In [65]:
np.vstack((arr1, arr2)) # size of array need to be same number of columns

array([[ 3,  2, -7],
       [ 5, -2, -5],
       [ 6,  7,  4],
       [ 8,  1,  2]])

In [67]:
np.hstack((arr1, arr2)) # same number of rows

array([[ 3,  2, -7,  6,  7,  4],
       [ 5, -2, -5,  8,  1,  2]])

In [73]:
np.concatenate((arr1, arr2), axis= 1)

array([[ 3,  2, -7,  6,  7,  4],
       [ 5, -2, -5,  8,  1,  2]])

In [71]:
np.concatenate((arr1, arr2)) ## same as vstack if axis=  1 then same as row

array([[ 3,  2, -7],
       [ 5, -2, -5],
       [ 6,  7,  4],
       [ 8,  1,  2]])