### 1. Elementwise Operations 

In [1]:
import numpy as np

In [3]:
a = np.array([[4,5,6], [5,7,9]])
b = np.array([[1,2,3], [5,6,7]])

In [5]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[1, 2, 3],
        [5, 6, 7]]))

#### Arithmetic Operations

In [6]:
# a + b
np.add(a,b)


array([[ 5,  7,  9],
       [10, 13, 16]])

In [18]:
# a - b
np.subtract(a,b)

array([[3, 3, 3],
       [0, 1, 2]])

In [9]:
# a*b
np.multiply(a,b)

array([[ 4, 10, 18],
       [25, 42, 63]])

In [11]:
# a ** b
# np.square(b)
np.power(a, 2)

array([[16, 25, 36],
       [25, 49, 81]])

In [16]:
np.divide(a,b)

array([[4.        , 2.5       , 2.        ],
       [1.        , 1.16666667, 1.28571429]])

In [15]:
# a % b
np.divmod(a,2)

(array([[2, 2, 3],
        [2, 3, 4]]),
 array([[0, 1, 0],
        [1, 1, 1]]))

In [17]:
np.abs(
    np.subtract(a,b)
)

array([[3, 3, 3],
       [0, 1, 2]])

In [22]:
qno, rem = np.divide(a, 2)

In [23]:
qno

array([2. , 2.5, 3. ])

In [24]:
rem

array([2.5, 3.5, 4.5])

In [25]:
np.ceil(np.sqrt(a))

array([[2., 3., 3.],
       [3., 3., 3.]])

#### Trignometric

In [27]:
new = 1 / np.sin(a)
print(new)

[[-1.32134871 -1.04283521 -3.57889955]
 [-1.04283521  1.52210106  2.42648664]]


In [28]:
1/ np.tan(a)

array([[ 0.86369115, -0.29581292, -3.436353  ],
       [-0.29581292,  1.14751542, -2.21084541]])

#### Round Operations

In [29]:
np.round(new, decimals= 3)

array([[-1.321, -1.043, -3.579],
       [-1.043,  1.522,  2.426]])

In [30]:
np.around(new, decimals= 3)

array([[-1.321, -1.043, -3.579],
       [-1.043,  1.522,  2.426]])

In [31]:
np.fix(new)

array([[-1., -1., -3.],
       [-1.,  1.,  2.]])

In [32]:
np.floor(new)

array([[-2., -2., -4.],
       [-2.,  1.,  2.]])

#### 2. Matrix Operations

In [39]:
a = np.array([[4,5,6], [5,7,9]])
b = np.array([[1,2,3], [9,8,7]])

In [40]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [41]:
a = np.array([[4,5,6], [5,7,9]])
b = np.array([[1,2,3], [9,8,7], [9, 4, 7]])

In [42]:
np.dot(a,b)

array([[103,  72,  89],
       [149, 102, 127]])

In [44]:
b

array([[1, 2, 3],
       [9, 8, 7],
       [9, 4, 7]])

In [45]:
# b.T
np.transpose(b)

array([[1, 9, 9],
       [2, 8, 4],
       [3, 7, 7]])

In [46]:
np.trace(b)

np.int64(16)

In [47]:
np.linalg.det(b)

np.float64(-79.99999999999997)

In [51]:
np.dot(
    b, np.linalg.inv(b)
).round()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
#solve Equations: x + 2*y = 1 and 3*x + 5*y = 2
a = np.array([[1,2],
             [3,5]])
b = np.array([1,2])

In [55]:
np.linalg.solve(a,b)

array([-1.,  1.])