In [1]:
import numpy as np

In [2]:
arr = np.random.randint(10,50, size = (5,2,3))
arr

array([[[27, 28, 23],
        [18, 29, 28]],

       [[41, 35, 38],
        [12, 39, 28]],

       [[20, 38, 38],
        [13, 30, 42]],

       [[43, 14, 39],
        [31, 32, 13]],

       [[27, 30, 40],
        [36, 22, 21]]])

In [3]:
arr.shape

(5, 2, 3)

In [4]:
arr.ndim

3

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr_T = arr.T
arr_T

array([[[27, 41, 20, 43, 27],
        [18, 12, 13, 31, 36]],

       [[28, 35, 38, 14, 30],
        [29, 39, 30, 32, 22]],

       [[23, 38, 38, 39, 40],
        [28, 28, 42, 13, 21]]])

In [7]:
arr_T.shape

(3, 2, 5)

In [8]:
arr.shape

(5, 2, 3)

In [13]:
arr.reshape(3, 5, 2)

array([[[27, 28],
        [23, 18],
        [29, 28],
        [41, 35],
        [38, 12]],

       [[39, 28],
        [20, 38],
        [38, 13],
        [30, 42],
        [43, 14]],

       [[39, 31],
        [32, 13],
        [27, 30],
        [40, 36],
        [22, 21]]])

In [10]:
arr.reshape(3, 10)

array([[27, 28, 23, 18, 29, 28, 41, 35, 38, 12],
       [39, 28, 20, 38, 38, 13, 30, 42, 43, 14],
       [39, 31, 32, 13, 27, 30, 40, 36, 22, 21]])

In [11]:
arr.reshape(10,3)

array([[27, 28, 23],
       [18, 29, 28],
       [41, 35, 38],
       [12, 39, 28],
       [20, 38, 38],
       [13, 30, 42],
       [43, 14, 39],
       [31, 32, 13],
       [27, 30, 40],
       [36, 22, 21]])