In [1]:
import numpy as np

In [2]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.full(shape = (2,2), fill_value = 7.8)

array([[7.8, 7.8],
       [7.8, 7.8]])

In [7]:
np.full(shape = (4,2,2), fill_value = 7.8)

array([[[7.8, 7.8],
        [7.8, 7.8]],

       [[7.8, 7.8],
        [7.8, 7.8]],

       [[7.8, 7.8],
        [7.8, 7.8]],

       [[7.8, 7.8],
        [7.8, 7.8]]])

### Accessing an Array

Indexing And Slicing Array

In [8]:
# 1D
a = np.array([1,2,3,4,6])

In [9]:
a

array([1, 2, 3, 4, 6])

In [10]:
a[0]

np.int64(1)

In [11]:
a[-1]

np.int64(6)

In [12]:
a[4]

np.int64(6)

In [33]:
b = np.random.randint(0,10,(5,5))

In [34]:
b

array([[9, 1, 1, 3, 7],
       [5, 2, 5, 1, 6],
       [4, 8, 0, 3, 1],
       [8, 5, 0, 3, 9],
       [9, 1, 7, 0, 6]])

In [17]:
b[1][0]

np.int64(9)

In [20]:
print(b[0][1]) #print gives output without np.int64

3


In [30]:
#3D
c = np.random.randint(0,10,(4,2,2))

In [31]:
c

array([[[8, 0],
        [1, 8]],

       [[1, 6],
        [6, 4]],

       [[4, 5],
        [6, 0]],

       [[7, 2],
        [6, 2]]])

In [23]:
c[-1][0][1]

np.int64(8)

#### Slicing
 same like in Python

In [24]:
a[2:4:1]

array([3, 4])

In [39]:
# Slicing 2D array : (array[<row_slice>, <column_slice>])
b[::2, 1:4]

array([[1, 1, 3],
       [8, 0, 3],
       [1, 7, 0]])

In [42]:
#3D Slicing 
c[::, ::, ::]

array([[[8, 0],
        [1, 8]],

       [[1, 6],
        [6, 4]],

       [[4, 5],
        [6, 0]],

       [[7, 2],
        [6, 2]]])

In [48]:
c[::, 0:2, 0:2]

array([[[8, 0],
        [1, 8]],

       [[1, 6],
        [6, 4]],

       [[4, 5],
        [6, 0]],

       [[7, 2],
        [6, 2]]])

In [50]:
c[::, 0:1, 0:2]

array([[[8, 0]],

       [[1, 6]],

       [[4, 5]],

       [[7, 2]]])

In [61]:
c[::, 0:2, 0:2]

array([[[8, 0],
        [1, 8]],

       [[1, 6],
        [6, 4]],

       [[4, 5],
        [6, 0]],

       [[7, 2],
        [6, 2]]])

In [62]:
d = np.random.randint(0,10,(16,3,500,500))

In [63]:
d

array([[[[2, 1, 0, ..., 2, 2, 0],
         [8, 4, 2, ..., 9, 9, 4],
         [4, 0, 2, ..., 8, 1, 7],
         ...,
         [4, 2, 5, ..., 3, 1, 4],
         [0, 3, 1, ..., 8, 0, 9],
         [1, 5, 5, ..., 3, 0, 2]],

        [[8, 8, 1, ..., 1, 9, 4],
         [6, 4, 2, ..., 6, 9, 5],
         [2, 6, 4, ..., 8, 3, 4],
         ...,
         [6, 9, 0, ..., 8, 0, 1],
         [3, 9, 6, ..., 8, 0, 6],
         [4, 9, 9, ..., 7, 3, 9]],

        [[7, 4, 9, ..., 8, 9, 8],
         [1, 6, 1, ..., 3, 2, 7],
         [2, 3, 9, ..., 8, 0, 0],
         ...,
         [5, 1, 9, ..., 2, 9, 8],
         [1, 8, 3, ..., 3, 7, 2],
         [2, 3, 7, ..., 5, 9, 3]]],


       [[[4, 1, 1, ..., 0, 9, 9],
         [9, 3, 1, ..., 2, 9, 2],
         [0, 9, 3, ..., 5, 8, 2],
         ...,
         [3, 7, 1, ..., 8, 8, 5],
         [7, 2, 8, ..., 3, 5, 7],
         [0, 2, 9, ..., 5, 3, 4]],

        [[7, 1, 0, ..., 0, 1, 5],
         [7, 7, 7, ..., 5, 9, 3],
         [8, 7, 4, ..., 7, 2, 7],
         ...,
  

In [65]:
d[::2]

array([[[[2, 1, 0, ..., 2, 2, 0],
         [8, 4, 2, ..., 9, 9, 4],
         [4, 0, 2, ..., 8, 1, 7],
         ...,
         [4, 2, 5, ..., 3, 1, 4],
         [0, 3, 1, ..., 8, 0, 9],
         [1, 5, 5, ..., 3, 0, 2]],

        [[8, 8, 1, ..., 1, 9, 4],
         [6, 4, 2, ..., 6, 9, 5],
         [2, 6, 4, ..., 8, 3, 4],
         ...,
         [6, 9, 0, ..., 8, 0, 1],
         [3, 9, 6, ..., 8, 0, 6],
         [4, 9, 9, ..., 7, 3, 9]],

        [[7, 4, 9, ..., 8, 9, 8],
         [1, 6, 1, ..., 3, 2, 7],
         [2, 3, 9, ..., 8, 0, 0],
         ...,
         [5, 1, 9, ..., 2, 9, 8],
         [1, 8, 3, ..., 3, 7, 2],
         [2, 3, 7, ..., 5, 9, 3]]],


       [[[7, 9, 0, ..., 1, 9, 3],
         [2, 0, 6, ..., 2, 7, 9],
         [4, 9, 9, ..., 1, 5, 3],
         ...,
         [7, 7, 2, ..., 9, 3, 6],
         [6, 3, 4, ..., 3, 0, 3],
         [6, 4, 3, ..., 5, 0, 9]],

        [[0, 5, 8, ..., 3, 6, 1],
         [9, 1, 6, ..., 6, 2, 7],
         [7, 7, 2, ..., 6, 2, 5],
         ...,
  

In [71]:
d[::2, ::, 0:10]

array([[[[2, 1, 0, ..., 2, 2, 0],
         [8, 4, 2, ..., 9, 9, 4],
         [4, 0, 2, ..., 8, 1, 7],
         ...,
         [9, 2, 8, ..., 8, 0, 3],
         [1, 6, 6, ..., 6, 7, 7],
         [9, 5, 7, ..., 0, 7, 7]],

        [[8, 8, 1, ..., 1, 9, 4],
         [6, 4, 2, ..., 6, 9, 5],
         [2, 6, 4, ..., 8, 3, 4],
         ...,
         [6, 7, 5, ..., 2, 0, 6],
         [0, 7, 9, ..., 9, 3, 2],
         [4, 8, 7, ..., 3, 0, 6]],

        [[7, 4, 9, ..., 8, 9, 8],
         [1, 6, 1, ..., 3, 2, 7],
         [2, 3, 9, ..., 8, 0, 0],
         ...,
         [4, 3, 7, ..., 5, 8, 4],
         [2, 4, 8, ..., 1, 5, 3],
         [1, 8, 1, ..., 9, 3, 6]]],


       [[[7, 9, 0, ..., 1, 9, 3],
         [2, 0, 6, ..., 2, 7, 9],
         [4, 9, 9, ..., 1, 5, 3],
         ...,
         [3, 9, 5, ..., 6, 1, 1],
         [7, 5, 4, ..., 0, 0, 9],
         [6, 4, 6, ..., 1, 9, 4]],

        [[0, 5, 8, ..., 3, 6, 1],
         [9, 1, 6, ..., 6, 2, 7],
         [7, 7, 2, ..., 6, 2, 5],
         ...,
  

#### Boolean or Mask Indexing

In [82]:
e = np.random.randint(1,7,(5,5))
e

array([[4, 2, 6, 4, 1],
       [4, 4, 6, 3, 1],
       [3, 1, 5, 2, 3],
       [4, 1, 4, 4, 2],
       [1, 3, 1, 1, 6]])

In [83]:
e >= 4 # check it's is greater or equal to 4 if yes return True otherwise False 

array([[ True, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [False, False,  True, False, False],
       [ True, False,  True,  True, False],
       [False, False, False, False,  True]])

In [84]:
mask = e >= 4

In [85]:
e[mask] #return only true value

array([4, 6, 4, 4, 4, 6, 5, 4, 4, 4, 6])

In [91]:
mask = [True, False, True, False, True]

In [92]:
e

array([[4, 2, 6, 4, 1],
       [4, 4, 6, 3, 1],
       [3, 1, 5, 2, 3],
       [4, 1, 4, 4, 2],
       [1, 3, 1, 1, 6]])

In [93]:
e[mask]

array([[4, 2, 6, 4, 1],
       [3, 1, 5, 2, 3],
       [1, 3, 1, 1, 6]])