In [1]:
import numpy as np

In [7]:
arr = np.random.randint(10,50, size = (5,2,3))
arr

array([[[23, 43, 47],
        [29, 13, 23]],

       [[45, 27, 39],
        [16, 24, 36]],

       [[29, 45, 28],
        [12, 42, 39]],

       [[10, 14, 40],
        [47, 27, 41]],

       [[30, 29, 33],
        [21, 28, 41]]])

In [3]:
arr.shape

(5, 2, 3)

In [5]:
arr.ndim

3

In [6]:
arr.dtype

dtype('int64')

In [11]:
arr_T = arr.T
arr_T

array([[[23, 45, 29, 10, 30],
        [29, 16, 12, 47, 21]],

       [[43, 27, 45, 14, 29],
        [13, 24, 42, 27, 28]],

       [[47, 39, 28, 40, 33],
        [23, 36, 39, 41, 41]]])

In [12]:
arr_T.shape

(3, 2, 5)

In [13]:
arr.shape

(5, 2, 3)

In [16]:
arr.reshape(3, 5, 2)

array([[[23, 43],
        [47, 29],
        [13, 23],
        [45, 27],
        [39, 16]],

       [[24, 36],
        [29, 45],
        [28, 12],
        [42, 39],
        [10, 14]],

       [[40, 47],
        [27, 41],
        [30, 29],
        [33, 21],
        [28, 41]]])

In [17]:
arr.reshape(3, 10)

array([[23, 43, 47, 29, 13, 23, 45, 27, 39, 16],
       [24, 36, 29, 45, 28, 12, 42, 39, 10, 14],
       [40, 47, 27, 41, 30, 29, 33, 21, 28, 41]])

In [18]:
arr.reshape(10,3)

array([[23, 43, 47],
       [29, 13, 23],
       [45, 27, 39],
       [16, 24, 36],
       [29, 45, 28],
       [12, 42, 39],
       [10, 14, 40],
       [47, 27, 41],
       [30, 29, 33],
       [21, 28, 41]])